version: '2'

services:
  fhqserver_db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: KzhyntJxwt
      MYSQL_DATABASE: fhqserver
      MYSQL_USER: fhqserver
      MYSQL_PASSWORD: VveGJemxFb
    networks:
      - fhqserver_net

  fhqserver:
    build: .
    depends_on:
      - fhqserver_db
    image: sea5kg/fhq-server:latest
    volumes:
      - "./data/public:/usr/share/fhq-server/public"
      - "./conf.d:/etc/fhq-server"
      - "./logs:/var/log/fhq-server"
      - "./ssl:/usr/share/fhq-server/ssl"
      # - "./fhq-server_data/web_admin_conf/fhq.ws.config.js:/usr/share/fhq-server/web-admin/fhq.ws.config.js"
      # - "./fhq-server_data/public:/usr/share/fhq-server/fhq-web-public"
      # - "./fhq-server_data/fhqjad-store:/usr/share/fhq-server/fhqjad-store"
    ports:
      - "1234:1234"
      - "4613:4613"
      - "7080:7080"
    restart: always
    networks:
      - fhqserver_net

  ext_nginx_node:
    image: nginx:1.16
    volumes:
      - "./nginx/html/:/usr/share/nginx/html"
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/logs:/var/log/nginx/"
      - "./ssl:/etc/nginx/ssl"
    restart: always
    ports:
      - "801:80"
      - "4431:443"
    networks:
      - fhqserver_net

networks:
  fhqserver_net:
    driver: bridge
